"""empty message

Revision ID: 3bffabe9a062
Revises: 889fa5cb9ce0
Create Date: 2021-03-16 22:10:34.339833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bffabe9a062'
down_revision = '889fa5cb9ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_name_key', 'favorites', type_='unique')
    op.drop_constraint('favorites_typeFav_key', 'favorites', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('favorites_typeFav_key', 'favorites', ['typeFav'])
    op.create_unique_constraint('favorites_name_key', 'favorites', ['name'])
    # ### end Alembic commands ###
