"""empty message

<<<<<<< HEAD:migrations/versions/e9237dcf8f40_.py
Revision ID: e9237dcf8f40
Revises: 
Create Date: 2021-03-16 20:27:31.850379
=======
Revision ID: 889fa5cb9ce0
Revises: 
Create Date: 2021-03-16 21:19:42.093708
>>>>>>> c22ef8b76ea01859cb2334a2bcd5ba75b50df335:migrations/versions/889fa5cb9ce0_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/e9237dcf8f40_.py
revision = 'e9237dcf8f40'
=======
revision = '889fa5cb9ce0'
>>>>>>> c22ef8b76ea01859cb2334a2bcd5ba75b50df335:migrations/versions/889fa5cb9ce0_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('typeFav', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('typeFav')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('users')
    # ### end Alembic commands ###
