"""empty message

Revision ID: f41b04ec181f
Revises: 341910180060
Create Date: 2021-03-16 18:49:24.067814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41b04ec181f'
down_revision = '341910180060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('typeFav', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'favorites', ['typeFav'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_column('favorites', 'typeFav')
    # ### end Alembic commands ###
